### ISSUE TITLE
App is not running.

### ISSUE THREAD

**Issue by mdaslamansari2008** [janaagaard75/expo-and-typescript#10]
Please put the exact steps to run the project. I am not able to run the project in the simulator. It was showing error when I type 

> yarn run ios
> yarn run v1.3.2
> error Command "ios" not found.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by janaagaard75** [comment]
For `yarn run ios` to work, `package.json` would have to include something like this AND `exp` would either have to be installed globally or added a dev dependency.

    "scripts": {
      "ios": "exp ios"
    }

This project is meant to be run using Expo XDE - simply because that's what I use - so I haven't set up shortcuts for running the project using the command line.

I'll look into this, but it will probably be a least a couple of weeks before I have time.

**Comment by mdaslamansari2008** [comment]
I will check. If I find the issue. I will send a PR. You can check and add it to Master.

**Comment by janaagaard75** [comment]
I've added `exp` as a dev dependency and updated the readme a bit, so I hope that this is enough to get people started.
