### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by elawhatson** [janaagaard75/expo-and-typescript#14]
hello @janaagaard75 , I want to make a logotype for your project, what do you think? your project is cool, but I think it may need a new face, so if you agree with this I can start with sketches. this is absolutely free and no compromises at all.😃

you can tell me what are your preferences and/or the colors that you want to have the logotype. regards.

**Comment by janaagaard75** [comment]
Hi @elawhatson. I think it sounds wonderful with a logo for this project!

I like the current trend with minimalistic icons, but as you can tell from the [current icon](https://github.com/janaagaard75/expo-and-typescript/blob/master/assets/icons/app-icon.png) I am not a designer, so pretty much anything will be better.

The current icons are scaled 192x192 pixels, so I guess this used to be a recommendation. The [current recommendation](https://docs.expo.io/versions/v30.0.0/guides/app-icons) is to create a logo that is 1024x1024 pixels (at least for the iOS App Store), but I don't think this app will ever get published to the official app stores. So I don't know what will work best, but let's figure that out later. After the redesign of Expo's page, the logo needs a background, since a transparent one doesn't look good any longer: <https://expo.io/@janaagaard75/expo-and-typescript>.

**Comment by elawhatson** [comment]
personally, I recommend that don't use icons from another tool or something for your app because loose originally and can be troubling legal or something, instead you can only specify the tools you use in the description of your app.

I've made this icon for your app, what do you think?

![expo-and-typescript](https://user-images.githubusercontent.com/43912079/46575204-f0ee2000-c97e-11e8-8d42-ce72857b40a0.png)

**Comment by janaagaard75** [comment]
Really good points about not including other icons. Thanks. 🙂

I like the icon, so unless you feel like tweaking it some more, I think we have a winner.

Will you make a pull request where you update the files in the `assets` folder?
