### ISSUE TITLE
Typescript module alias config ?

### ISSUE THREAD

**Issue by diegolaciar** [janaagaard75/expo-and-typescript#21]
Hi,

I would like to config module alias, can you provide an example? how to do it with expo & typescript?

Thanks,
Diego

I tried changing the tsconfig.json as. 

"baseUrl": "src",
"paths": {
  "@models/*": ["models/*"],
  "@components/*": ["components/*"],
  "@plugins/*": ["plugins/*"],
}

**Comment by janaagaard75** [comment]
I don't use module aliases myself, so take everything below with a grain of salt.

I looks like you're missing some asterisks in your `paths` section.

    "baseUrl": "src",
    "paths": {
      "@models/*": ["models/*"],
      "@components/*": ["components/*"],
      "@plugins/*": ["plugins/*"],
    }

I got the info from [path mapping from the TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) and this [answer on Stack Overflow](https://stackoverflow.com/a/43330003/37147).

I don't think that using a `paths` section like the one above will make your imports any shorter though, since replacing `models` with `@models` is actually one character more. If this is about using absolute paths I would assume that there is a simpler way than having to list every top level folder that you have in `src`.

It looks like you want to group your files by type. Personally, I would recommend grouping by feature, as described in [Grouping by features or routes](https://reactjs.org/docs/faq-structure.html#grouping-by-features-or-routes). Whatever grouping solution you end up choose, I would definitely recommend to start out **without** any grouping. So just put all the files in `src`, and as the number of files in the folder grow, it should be quite obvious how they can be grouped.

**Comment by janaagaard75** [comment]
Can I close this issue, @diegolaciar?

**Comment by diegolaciar** [comment]
@janaagaard75  thanks for your response!

You are right, that is the way to config alias with TS.
But looks like babel part doesn't like and the app don' t load that way ?

Sounds to me like the alias have to be configured somehow in babel. But I couldn't make it work! .

It would be very nice to know how to use that feature in expo/TS projects.

### The temporary solution was to config Absolute Paths.
I had to create a file package.json  in src  directory with this content.
```javascript
{"name": "src"}
```

then import like this from everywhere in the project ej:  

```javascript
import { someFunction, myOtherFunction } from "src/utils";
```

Would be good for me to leave this issue open; maybe someone who know how to config alias on a expo-TS project can contribute and close the issue.

**Comment by dalcib** [comment]
You need to configure Metro with ``extraNodeModules`` prop.
https://facebook.github.io/metro/docs/en/configuration

```
// metro.config.js
module.exports = {
  resolver: {
    '@org/module': path.resolve(__dirname, "wherever")
  }
};
```

**Comment by janaagaard75** [comment]
Can I close this issue, @diegolaciar?

**Comment by dmydry** [comment]
+1 guys, I just started with expo and typescript.
It's not that obvious about module resolution in expo without deeping into their internals. 
So with @dalcib suggestion with `metro.config.js` it's not enough in my case.

Let's make an example with just a simple app structure, for example:
```
src/App.tsx
src/components/Tab1.tsx
src/components/Tab2.tsx
```

So we can just make imports in App.tsx like so
```
import { Tab1 } from 'src/components/Tab1';
import { Tab2 } from 'src/components/Tab2';
```

By the way @janaagaard75 thanks, great job!

**Comment by janaagaard75** [comment]
Can I close this issue, @diegolaciar?

**Comment by diegolaciar** [comment]
yes,  thanks @janaagaard75

**Comment by dmydry** [comment]
For those who will look for a solution, it's pretty simple:

In your tsconfig.json
```
  "compilerOptions": {
    "paths": {
      "components/*": ["src/components/*"],
      [...other_paths]
    }
```

In your babel.config.js
```
    plugins: [
      [
        'module-resolver',
        {
          extensions: [
            '.js',
            '.jsx',
            '.ts',
            '.tsx',
            '.android.js',
            '.android.tsx',
            '.ios.js',
            '.ios.tsx',
          ],
          root: ['./src'],
          alias: {
            components: './src/components',
            [...other_aliases]
          },
        },
      ],
    ],
```

**Comment by janaagaard75** [comment]
That's a pretty big repo you're linking to, @dagatsoin. When I try to build the code (`npm run build`), I get no less than 17 errors. I guess that there are some global dependencies, that I haven't installed.

I would recommend that you create a branch in this repository or create a new repository, where you remove as much code as possible, so that it is easier for someone else to help you pinpoint where the error is.

**Comment by dagatsoin** [comment]
During repro minimization, I find that I have circular dependencies. The strange thing is that w when using work in my webpack env when developing the web side of my project.
Anyway, thanks you for your indirect help @janaagaard75 :

For the log, I just set my path alias in tsconfig.json and it works.

```
"baseUrl": "./",
"paths": { 
    "sproutch": ["./src/vendor/sproutch"]
}
```

**Comment by vietnogi** [comment]
It dosnt seem like any changes to tsconfig.config have an affect.

Added `"baseUrl": "src",` and modified `import { AssetScreen } from './AssetScreen'` to `import { AssetScreen } from 'AssetScreen'` and get a `Unable to resolve` error.

**Comment by vietnogi** [comment]
@dmydry works for `components` but if you were to change to `componentts`, it will no longer work.  I have a feeling that `components` is a special keyword.

**Comment by vietnogi** [comment]
Ok! Figured it out.  `tsconfig` is not used to resolve path because expo is using babel.  `extensions` is required in the babel config per @dmydry example.  The problem is that there's caching issues with expo.  Make sure you run `rm -rf /tmp/metro-bundler-cache-*` and `rm -rf /tmp/haste-map-react-native-packager-*` when testing the babel config.  On top of that, I had to make a change in one of my source files (probably to trigger watchman) to get rid of the error in the emulator.

**Comment by janaagaard75** [comment]
Thanks a lot for posting the answer. Hope it will help others. 🙂

**Comment by PavelPolyakov** [comment]
I this approach still working? And how can I debug it.

I've put a @dmydry's snippet into my babel, and am even sure that that `babel.config.js` is executed (put some `console.log` inside), but the error is the same.

```js
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      [
        'module-resolver',
        {
          extensions: [
            ".js",
            ".jsx",
            ".ts",
            ".tsx",
            ".android.js",
            ".android.tsx",
            ".ios.js",
            ".ios.tsx"
          ],
          root: ["./src"],
          alias: {
            '@entities': "./entities",
            '@interfaces': "./@types/interfaces"
          }
        }
      ]
    ]
  };
};
```

Regarding @vietnogi's note - I don't see any cache in `/tmp`.

Any hints how can I debug this?

**Comment by janaagaard75** [comment]
Thanks a lot for updating your post with the solution that you found, @PavelPolyakov.

**Comment by excitedcat** [comment]
This works:

```js
alias: {
   '@test': './src/components'
}
```

```js
import { getTabBarIcon } from '@test/tabbar'
```

This works:

```js
alias: {
   components: './src/components'
}
```

```js
import { getTabBarIcon } from 'components/tabbar'
```

But this can not work: ????
```js
alias: {
   '@components': './src/components'
}
```

```js
import { getTabBarIcon } from '@components/tabbar'
```

**Comment by serusko** [comment]
looks like not working on sdk 37 anymore

**Comment by janaagaard75** [comment]
Do you have a repo you can link to, @serusko?

**Comment by serusko** [comment]
lol, today its working, when i added `babel-plugin-module-resolver` insted od `module-resolver` it started work, i think there is some kind of cache, bcs i tried same config yesterday
babel:
```
plugins: [
  "babel-plugin-module-resolver",
  { extensions: [".js", ".jsx", ".ts", ".tsx"], root: ["./src"] },
],
```
tsconfig
```
"baseUrl": "./src"
```
and thats all, working example
```
import DetailScreen from "views/Detail";
import ErrorBoundary from "components/ErrorBoundary";
````

**Comment by Rechdan** [comment]
> lol, today its working, when i added `babel-plugin-module-resolver` insted od `module-resolver` it started work, i think there is some kind of cache, bcs i tried same config yesterday
> babel:
> 
> ```
> plugins: [
>   "babel-plugin-module-resolver",
>   { extensions: [".js", ".jsx", ".ts", ".tsx"], root: ["./src"] },
> ],
> ```
> 
> tsconfig
> 
> ```
> "baseUrl": "./src"
> ```
> 
> and thats all, working example
> 
> ```
> import DetailScreen from "views/Detail";
> import ErrorBoundary from "components/ErrorBoundary";
> ```

Do yours still work? I can't figure what I'm doing wrong here:
```js
module.exports = function (api) {
	api.cache(true);

	return {
		presets: ['babel-preset-expo'],
		plugins: [
			[
				'module-resolver',
				{
					root: ['./src'],
					extensions: ['.js', '.jsx', '.ts', '.tsx'],
					alias: {
						assets: './assets',
						src: './src',
					},
				},
			],
		],
	};
};
```

**Comment by janaagaard75** [comment]
> Do yours still work?

I think question is to you, @serusko.

**Comment by hu-tu-yi-shi** [comment]
work for me  ,  https://gist.github.com/ChronSyn/ffca12630eb36c71465a1c5d7149a6ae
