### ISSUE TITLE
TSLint Airbnb

### ISSUE THREAD

**Issue by mauriciord** [janaagaard75/expo-and-typescript#40]
Is there any way of integration with Airbnb TS Styleguide?

**Comment by janaagaard75** [comment]
What exactly do you mean, @mauriciord? [Airbnb's JavaScript Style Guide](https://github.com/airbnb/javascript) is, as the name suggest, intended for JavaScript and not TypeScript. I don't think there is a TypeScript version. So by that regard the answer would be "no". That being said, since the two languages are so similar, most of the recommendations in it also apply to TypeScript, and I actually think that the code in this repository already mostly follows the guide. Do you have anything particular in mind?

If you are asking if [tslint-config-airbnb](https://github.com/progre/tslint-config-airbnb/#readme] could be turned on, assume that the answer is "yes". I recently switched from TSLint to ESLint, though, since [TSLint is being deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), but that doesn't block you to going to back to using TSLint.

**Comment by janaagaard75** [comment]
Does this answer your question? Can I close this issue, @mauriciord?

**Comment by mauriciord** [comment]
Yep @janaagaard75
