### ISSUE TITLE
merge with @types/expo

### ISSUE THREAD

**Issue by mzgnr** [janaagaard75/expo-and-typescript#8]
There is also https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/expo . Would you like to merge  ?

**Comment by janaagaard75** [comment]
@types/expo didn't exist when I started this project.

I think merging this into DefinitelyTyped is a great idea, but in practice it seems like it's quite a big task. I don't know how far the other project is, so I am not really sure how to best proceed. Suggestions are very welcome.

**Comment by mzgnr** [comment]
I've not tested `@types/expo` yet but I think we can copy and paste from it ( should give credits ). I saw that some of the missing definitions in your project exists in `@types/expo` (like DocumentPicker, facebook ads ) . With this way we can have more complete package fast.

**Comment by janaagaard75** [comment]
I think the best approach is to cherry pick the missing definitions, and import them into this repo. I really like keeping a consistent style through the code, so that would have to be updated.

It looks like <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expo/index.d.ts> is also based on <https://gist.github.com/pierre-H/eef9a9225fb1c5a0f81180a8b0fbb2c2>, as it's the case with this repo, so the type definitions for DocumentPicker and FacebooksAds in here are the same as the ones on `@types/expo`. The reason I haven't put a check mark on on the list in the readme for this repo, it that is was my experience that the definitions had become outdated.

**Comment by razagill** [comment]
Just FYI: tried the definitions from `@types/expo` and they don't have types for `@expo/vector-icons`. The file in this repository does.

**Comment by janaagaard75** [comment]
Yes. We need to make pull requests to migrate the changes made in this repo in into `@types/expo`. If you have any free time, help would greatly appreciated.

**Comment by mzgnr** [comment]
@janaagaard75 I'm working on a project currently using Admob and Facebook ads. I can work on these definition types. The problem for me is d.ts file is too long to handle. Can we split into different d.ts files and import them into expo.d.ts file ?

**Comment by janaagaard75** [comment]
Regarding `react-native-vector-icons`: It's my experience that you the type definitions for the Expo SDKs have to be fine tuned a bit, in order to work. Expo has done all of the setting up, so that things work out of the box, but that means that you have to import from `'expo'`, and thus that the type definitions have to be different - even if it's just a matter of a different namespace. I'm pretty sure the Expo team is using `react-native-vector-icons` behind the scenes, or at least have been inspired by that project.

**Comment by janaagaard75** [comment]
Regarding splitting the type definitions into separate files, I've actually asked that exact question on Stack Overflow: <https://stackoverflow.com/q/47393700/37147>. The only answer that I got was to do something like this: <https://stackoverflow.com/a/37684736/37147>. That strategy might work nicely for the `@types/expo` project, but I decided against it here, since that would make it annoying when you have to update all the type definitions files manually. I also considered making a custom file merge build step, but never got around to actually trying anything out.

I you want to type definitions, I think you should make pull requests for `@types/expo` instead of this repo, since I that is of course going to be the repo where people expect to find the type definitions, and it's a lot easier to use, since it has the special `@types` prefix. I regret that I didn't just start out adding the type definitions there, because now someone else has created `@types/expo`.

**Comment by janaagaard75** [comment]
The status is that most of the changes in this repo has been merged into `@types/expo`. Some things are still missing, though, so the code in here does not compile if you replace `expo.d.ts` with the one from `@types/expo`.

I'll keep this issue open until everything has been resolved.

**Comment by janaagaard75** [comment]
All the type definitions in have been merged into `@types/expo`, and this code no longer needs custom type definitions, so closing this issue.
