### ISSUE TITLE
clarify hot reloading

### ISSUE THREAD

**Issue by vonovak** [janaagaard75/expo-and-typescript#9]
the readme states "Hot reloading and debugging of TypeScript files works, but hot module replacement does not work." the two things, at least as I see them, are equivalent, so the question of whether hot reload work remains unanswered. Thanks.

**Comment by janaagaard75** [comment]
You're absolutely right! What I meant is that the app automatically reloads whenever you make a change in the code, and I thought that this was called "hot reloading", but that is not correct. I haven't tried React Native in plain JavaScript, so I don't know if the experience is less smooth when coding in TypeScript. Reloads are faster than the initial load, but I guess this is because the Expo client can cache some of the resources.

Thanks a lot for pointing this out. I've updated the readme to reflect his.
